### ISSUE TITLE
inserter.d(210,9): Error: no property 'execute' for type 'Connection!(VibeSocket, cast(ConnectionOptions)0)**'

### ISSUE THREAD

**Issue by crimaniak** [eBookingServices/mysql-lited#10]
After upgrade from 0.3.15 to 0.3.16 I got an error:
../../.dub/packages/mysql-lited-0.3.16/mysql-lited/src/mysql/inserter.d(210,9): Error: no property 'execute' for type 'Connection!(VibeSocket, cast(ConnectionOptions)0)**'
source/vcm/sqlWrapper.d(59,31): Error: template instance mysql.inserter.inserter!(Connection!(VibeSocket, cast(ConnectionOptions)0)*, string[]) error instantiating
source/updater/action/addRecords.d(22,12):        instantiated from here: insert!(int, string)
...
It was o.k. in 0.3.15
